/* CertHub service worker — generated by build.js. Do not edit by hand. */
var VERSION = "certhub-1783069097857";
var CORE = ["./","assets/css/styles.css","assets/js/app.js","assets/js/lib/feedback.js","assets/data/content-data.js","assets/data/search-index.js","assets/favicon.svg","manifest.webmanifest"];

self.addEventListener("install", function (e) {
  self.skipWaiting();
  e.waitUntil(
    caches.open(VERSION).then(function (c) {
      return Promise.all(
        CORE.map(function (u) {
          return c.add(u).catch(function () {});
        })
      );
    })
  );
});

self.addEventListener("activate", function (e) {
  e.waitUntil(
    caches.keys().then(function (keys) {
      return Promise.all(
        keys.map(function (k) {
          if (k !== VERSION) return caches.delete(k);
        })
      );
    }).then(function () { return self.clients.claim(); })
  );
});

self.addEventListener("fetch", function (e) {
  var req = e.request;
  if (req.method !== "GET") return;
  var url = new URL(req.url);
  if (url.origin !== location.origin) return;
  e.respondWith(
    caches.open(VERSION).then(function (cache) {
      return cache.match(req).then(function (cached) {
        var network = fetch(req)
          .then(function (res) {
            if (res && res.status === 200 && res.type === "basic") {
              cache.put(req, res.clone());
            }
            return res;
          })
          .catch(function () { return null; });
        return (
          cached ||
          network.then(function (res) {
            return res || cache.match("./");
          })
        );
      });
    })
  );
});
